version: '3'
services: 
  mongodb:
    image: mongo
    #restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=denoexampledb

  mongo-express:
    image: mongo-express
    #restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    depends_on:
      - mongodb

  app:
    build: .
    ports:
      - 4000:4000
    environment:
      - DB_URL=mongodb://admin:password@mongodb:27017
    depends_on:
      - mongodb
